### ISSUE TITLE
Compiler class ambiguity

### ISSUE THREAD

**Issue by FranksNix** [cjvandyk/Extensions#2]
**Describe the bug**
When including the Extensions.dll and defining a new string object like this
`String mystring = "Hello";`
then the system complains about class ambiguity and I have to change my code to
`System.String mystring = "Hello";`
for it to work. That adds extra tedium to usage.

**To Reproduce**
1. Create a new console app project
2. Add the Extensions.cs NuGet package
3. Add using Extensions; to the top of the code
4. Define a new variable like so `String mystring = "Hello";`
5. Compile
6. See error

**Expected behavior**
I don't expect to be forced to define System with variables. That is what the using statement is for.

**Comment by cjvandyk** [comment]
Hello Frank.  Thanks for the heads up.  Personally I always use C style "string" which explains how it fell through a testing crack.  The refactored version will drop with the 2.2 NuGet release tomorrow.
https://www.nuget.org/packages/Extensions.cs

**Comment by cjvandyk** [comment]
Bug fixed in https://www.nuget.org/packages/Extensions.cs/2.2.480 version.

**Comment by FranksNix** [comment]
Thx
