### ISSUE TITLE
Only supports .NET Framework 4.8

### ISSUE THREAD

**Issue by BillZulu** [cjvandyk/Extensions#3]
Extensions.dll supports only 4.8.  Can you support more frameworks?

**Comment by cjvandyk** [comment]
As of version 2.3.500 (https://www.nuget.org/packages/Extensions.cs/2.3.500), we now support .NET versions 3.5, 4.03, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 5.0!
